### ISSUE TITLE
(Suggestion) Imperial units support

### ISSUE THREAD

**Issue by alpacathunder1** [spech66/lifelogspd#1]
Thank you so much for this app!

I've had fun playing around with it and would love to deploy it on my home server, but unfortunately being here in the US everything is in pounds rather than kilograms, so it would mean converting the units for each set--which would get tedious after awhile.

It would be great to have some sort of global toggle in a config file to support this or something similar.

Thanks for reading!

**Comment by spech66** [comment]
Hi @alpacathunder1 the imperial units support is one of the next todos in the https://github.com/spech66/lifelogbb project.
