### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by alexkutsan** [spech66/lifelogspd#3]
This service is awesome. 
There are no self-hosted/open-source alternatives to it.  
But to make it ready for use it needs authentication.

**Comment by alexkutsan** [comment]
Also, auth must support creating API_KEY, so that it would be easy to add records automatically via HTTP API

**Comment by spech66** [comment]
Thank you for the ideas. I'm currently working on a new version of this incorporating API/Swagger/SQLite.

**Comment by spech66** [comment]
Hi @alexkutsan authentication is now directly build in in the new https://github.com/spech66/lifelogbb project.
